### ISSUE TITLE
Phaser入门资料

### ISSUE THREAD

**Issue by qiangzi7723** [GuangZhouShanyouGame/Document#1]
## Playcanvas开发

由于部分同学之前没有接触过正式的游戏开发 所以贸然的让你们去学Playcanvas难度会太高 所以公司决定先让大家熟悉Phaser这个2D的游戏引擎 等到熟悉了这个引擎的思想之后再转去学Playcanvas的开发

## Playcanvas官网地址

>>https://playcanvas.com/

Playcanvas官网上目前还挂着我们公司新开发的两款游戏 有兴趣的可以去看一下

## Phaser官网地址

>>http://www.phaser.io/

## 入门视频

>>http://search.jikexueyuan.com/course?q=phaser

极客学院上有一个讲解Phaser的入门视频不错 基本涵盖了Phaser中的大部分内容 入门方面的话可以趁没入职之前花时间把整套视频过一遍 开发的时候结合Phaser文档参考进行开发 有不懂的地方要多查文档 如果是mac系统的话 推荐一个dash软件 里面有收录Phaser的开发文档 可以进行全局搜索 windows方面就可以从github上面把Phaser的文档拉到本地进行查阅 不用每次都是在官网上查 毕竟如果电脑没翻墙的话访问Phaser官网的速度也不快 我这边已经发了一份本地的Phaser文档给大家 如果学习的过程中对Phaser的某个点不是很懂 这个时候还可以参考Phaser官网的例子 官网贴出来的例子是很丰富的 涵盖了很多知识点 比如 如果你看文档中 对于Phaser的debug接口不是很了解 那么就可以去官网贴出的例子中找到debug这一块结合看一下 我这边也发了一份Phaser官网例子的本地版本过去

## 跑酷游戏

发过去的资料中 还有一个本地版本的跑酷游戏 这个游戏是我刚入职的时候写的第一个游戏 而且当时的开发周期也比较紧 一周开发两个游戏 当时也还处于对Phaser的摸索中 所以这个游戏的代码质量不会特别好 但是也是因为是入门的时候马上写的 所以对于入门而言可能看起来也会相对的轻松点 为了能够容易看懂 我整个游戏加了很多注释 大家可以结合着文档看这个游戏 这个游戏是基于我们现在的24好玩平台旧的脚手架进行二次开发的 旧的脚手架存在的问题就是 我们使用Phaser开发完成之后的游戏 接上我们的24好玩平台的这个过程会比较复杂麻烦 所以公司最近正在开发一套新的脚手架 为的就是能够让大家以后接脚手架的时候能够轻松很多 新的脚手架还没开发完成 所以也没法在文档中跟大家讲太多脚手架的事情 目前你们需要的就是专注Phaser的开发

### 问题分析
因为canvas不是矢量图，而是像图片一样是位图模式的。如果不做Retina屏适配的话，例如二倍屏，浏览器就会以2个像素点的宽度来渲染一个像素，该canvas在Retina屏幕下相当于占据了2倍的空间，相当于图片被放大了一倍，因此图片会变模糊。

### 解决办法
要设置canvas的画布大小，使用的是canvas.width 和 canvas.height；

要设置画布的实际渲染大小，使用的style或CSS设置的 width 和height，只是简单的对画布进行缩放。

代码：

	<canvas width="640" height="800" style="width:320px; height:400px"></canvas>

现在平台上用的方法就是获取设备的宽高 然后把宽高＊2赋给画布

    this.canvasSize.width = window.innerWidth * 2;
    this.canvasSize.height = window.innerHeight * 2;
    $(game.canvas).css("width", self.canvasSize.width / 2);
	$(game.canvas).css("height", self.canvasSize.height / 2);
	
这个适配的问题在到时候的Playcanvas的开发中也会遇到，当时是麦乐踩这个坑，找了好久才找到在Playcanvas上的解决方案。

如果我们使用了这种设置canvas画布大小两倍的方法去解决Retina屏上canvas变糊的问题，那么存在新的问题，Phaser官网上的那份源码与这种设置有冲突 存在着一个小的BUG 这个BUG直到现在都没有被修复 公司针对这个BUG改了Phaser源码 这份源码我也发给了你们 尽量使用这份缘码进行开发

## 基于手机端的开发

由于我们公司游戏模版针对的平台是手机端 微信端等的 所以大家在进行Phaser的学习过程中 如果想试着去开发一些小游戏 尽量是基于手机端的 同时基于手机端开发的游戏也是最难的 因为手机存在性能瓶颈以及适配缩放等问题 适配和缩放这些都比较简单 大家需要注意的是开发的过程中留意一下性能方面的问题 做好垃圾回收 游戏中超出了屏幕外的障碍物等要及时删除 还要减少计算量等等

---

## 开始
	<!DOCTYPE html>
	<html lang="en">
	<head>
	    <meta content="yes" name="apple-mobile-web-app-capable"/>
	    <meta content="yes" name="apple-touch-fullscreen"/>
	    <meta content="black" name="apple-mobile-web-app-status-bar-style">
	    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	    <meta charset="UTF-8">
	    <title>Title</title>
	    <style>
	        html,body{margin:0;}
	    </style>
	</head>
	<body>
	    <div id="game"></div>
	    <script src="zepto.js"></script>
	    <script src="phaser-2.6.2.min.js"></script>
	    <script src="index.js"></script>
	</body>
	
	</html>

## 关于脚手架

我发过去的资料中 还有一份叫做得分类的phaser.js 这就是我上面提到的公司旧的脚手架 新的脚手架还在开发 虽然说这份脚手架是旧的 但是它的功能是十分齐全的 拥有音乐管理器 已经写好了4个场景 boot preload create play等等 并且定义好了加载画面 以及修复了上面提到的Retina屏幕资源模糊等等问题 并且这份脚手架也是十分适合本地开发的 所以我就把它也发给大家了 注释的内容很多 因为现在是不考虑接平台 你们需要熟悉的就是单纯的使用Phaser在本地进行开发 所以对于脚手架中注释的内容你们不需要太过担心 整个脚手架的流程就是 （下面内容结合脚手架那份脚本一起看）

	$(document).ready(function() {
	    gameManager = new Game();
	    gameManager.init();
	});
	
页面加载完毕后执行init方法

	init : function() {
	        var self = this;
	        // 初始化设备信息
	        this.initDevice();
	        // 初始化画布大小
	        this.initCanvasSize();
	        // 设置已进入初始化阶段
	        this.isInit = true;
	        // 创建游戏实例
	        this.instance = new Phaser.Game(this.canvasSize.width, this.canvasSize.height, Phaser.CANVAS, this.domId);
	        // 创建游戏状态
	        this.instance.States = {};
	
	        var game = this.instance;
	        // State - boot
	        // 加载加载页所需资源
	        game.States.boot = function() {
	            this.preload = function() {
	                // 设置画布大小
	                $(game.canvas).css("width", self.canvasSize.width/2);
	                $(game.canvas).css("height", self.canvasSize.height/2);
	                // 设置默认背景颜色
	                game.stage.backgroundColor = '#aaa';
	            };
	            this.create = function() {
	                // 进入preload状态
	                game.state.start('preload');
	            };
	        };
	        
	      
init方法中先解决Retina屏幕问题 然后通过`new Phaser.Game(this.canvasSize.width, this.canvasSize.height, Phaser.CANVAS, this.domId)`初始化Phaser对象 执行boot场景里面的`this.preload`函数 设置背景色 然后执行`this.create`跳转到下一场景

	game.States.preload = function() {
	            this.preload = function() {	       
这一场景主要是预加载资源 游戏中需要用到的图片资源 音频资源都是在这里进行预加载的 进度条会根据预加载资源的情况显示进度条动画
     
    // 全部文件加载完成
    game.load.onLoadComplete.add(callback);
    // 文件加载完成
    game.load.onFileComplete.add(function(progress){
        $('.bar').width(2.6*progress/100 + 'rem');
    });
    
资源以这种方法加载进来    

    // game.load.image('minus', "assets/images/minus.png");
    //加载音效
    // game.load.audio('bgMusic',"assets/bg.mp3");

其中资源中 前面的minus bgMusic指代的是这个资源的key值 可以理解为名字 之后需要使用该资源时都是通过传进这个key值使用

资源加载完毕之后回调callback函数`game.state.start('create');`进入下一个场景

    game.States.create = function() {
        this.create = function() {
            // 测试用 - 直接进入play状态
            game.state.start('play');

            // 上线用
            // 创建音乐管理器，传入的第三个参数是音乐的key
            // self.musicManager = new MusicManager(game, self.device, ['bgMusic','click']);
            // 显示开始菜单页面 使用dom构建
            // if (skip) { // 如果是工作台里面的直接进入游戏界面
            //  game.state.start('play');
            // } else {
            //  $('#start-menu').show();
            // }
        }
    };
    
create场景时初始化音乐管理器 如果游戏中需要使用音乐时 需要自行把musicManager注释掉 至于另外被注释的代码段skip就暂时不需要了解 这是之后接24好玩平台的事情

接下来就到了play场景 我们一般都是把整个游戏的逻辑都写在这里面 可以把前面的几个场景理解为游戏初始化之前的一些准备工作 游戏的功能都是写在该场景中的 所以对于这个场景也没什么好说的 这里面的代码就是大家需要写的

至此 脚手架的简单使用讲解完了 如果有不懂的地方可以及时在微信群上反馈提问 我和麦乐看到了信息会及时回复 我是强子 微信昵称脚皮哥 当然 大家也可以不使用脚手架做二次开发 脚手架只是解决了部分重复的工作 如果有人觉得脚手架太过复杂或者麻烦 也可以按照自己的想法进行资源加载 场景创建等等   

#### 什么是合图

合图就比如我们的跑酷游戏中 人物走路的动画就是由两帧的图片组成 然后人物跳跃的动画又是一张角色的图片 这种如果使用合图的话就很容易完成 因为Phaser封装了这样的方法 可以很容易的操作图片

>>TexturePacker

如果游戏中需要用到合图的话 使用TexturePacker这个工具 网上进行下载 目前平台也是使用这个工具在后台进行合图 所以我们要跟平台那边统一 这个的具体原因到时候培训的时候会讲

合图工具需要注意的地方就是 Data Format 格式记得要选 JSON(Array) 格式

## 最后

我还给了一个文件夹 是flappy bird的资源 希望大家可以趁这段时间多熟悉Phaser 然后顺便把flappy bird这个小游戏给做出来练一下手 很简单的一个游戏 图片以及音频资源都放在里面了 博客园上面无双写了一个关于用Phaser做这个游戏的简单的教程 但是他上面的做法是有问题的 并没有很好的处理好资源模糊的问题

这个是游戏的试玩地址

>>http://chaping.github.io/game/flappy-bird/

这个是无双的教程

>>http://www.cnblogs.com/2050/p/3790279.html

希望大家能够根据游戏的试玩地址然后独立的把游戏给写出来 尽量不要去看别人的源码 毕竟以后的游戏都是需要你们自己写的 没有代码可以参考 如果连这第一步都跨不出 以后学Playcanvas做3D游戏更难 

另外 记得多看Phaser文档 你们不懂的API文档上都有 加油

**Comment by WingMrL** [comment]
我已经整理了了一份md格式了。
